import { useDocumentMetadata } from '../hooks/useDocumentMetadata';
import './legal.css';

export function TermsConditions() {
  useDocumentMetadata(
    'Terms & Conditions | Calsi',
    'Read Calsi\'s Terms and Conditions. By using our financial calculator tools, you agree to these terms of service.'
  );

  return (
    <div className="legal-page">
      <div className="legal-header">
        <h1 className="legal-title">Terms &amp; Conditions</h1>
        <p className="legal-subtitle">Last updated: June 12, 2026</p>
      </div>

      <div className="legal-body">

        <section className="legal-section">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using <strong>Calsi</strong> ("the Service"), available at{' '}
            <strong>calsi.vercel.app</strong>, you agree to be bound by these Terms and Conditions ("Terms").
            If you do not agree to these Terms, please refrain from using the Service.
          </p>
          <p>
            These Terms constitute a legally binding agreement between you ("User") and Calsi ("we," "our," or "us").
            We reserve the right to modify these Terms at any time. Continued use of the Service after modifications
            constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section className="legal-section">
          <h2>2. Description of Service</h2>
          <p>
            Calsi provides free, browser-based financial calculators including tools for SIP, Lumpsum, EMI, FD, RD,
            PPF, EPF, SSY, SWP, Mutual Fund Returns, GST, and XIRR calculations. The Service is provided for
            general informational and educational purposes only.
          </p>
          <p>
            All calculations are performed client-side within your browser. We do not store, transmit, or have
            access to any financial data you enter into our calculators.
          </p>
        </section>

        <section className="legal-section">
          <h2>3. Disclaimer of Financial Advice</h2>
          <div className="legal-warning-box">
            <p>
              <strong>IMPORTANT:</strong> Calsi is NOT a registered financial advisor, investment advisor,
              broker, or tax consultant. The calculators and results provided by the Service are for
              <strong> illustrative and informational purposes only</strong> and do not constitute financial,
              investment, tax, or legal advice.
            </p>
          </div>
          <p>
            The results generated by our calculators are based on the inputs you provide and mathematical
            formulas. Actual investment returns, interest rates, and financial outcomes may differ significantly
            due to market volatility, changes in interest rates, inflation, tax laws, and other factors.
          </p>
          <p>
            We strongly recommend consulting a qualified financial advisor, chartered accountant, or tax
            professional before making any investment, financial, or tax decisions.
          </p>
        </section>

        <section className="legal-section">
          <h2>4. Accuracy of Information</h2>
          <p>
            We endeavour to ensure the accuracy of our calculators and the information provided on the Service.
            However, we make no warranties or representations, express or implied, regarding:
          </p>
          <ul>
            <li>The accuracy, completeness, or reliability of any calculation results.</li>
            <li>The suitability of the Service for any particular financial decision or purpose.</li>
            <li>The currency of information, including interest rates or regulatory provisions (e.g., PPF rate of 7.1% p.a.), which may change without notice.</li>
          </ul>
          <p>
            Interest rates used in our calculators (such as PPF at 7.1% or SSY at 8.2%) reflect publicly
            available rates as of the last update and may not reflect the most current rates. Always verify
            rates with the relevant financial institution or government source before making decisions.
          </p>
        </section>

        <section className="legal-section">
          <h2>5. User Responsibilities</h2>
          <p>By using the Service, you agree to:</p>
          <ul>
            <li>Use the Service for lawful purposes only and in accordance with these Terms.</li>
            <li>Not attempt to reverse engineer, decompile, or exploit any part of the Service.</li>
            <li>Not use automated tools, bots, or scrapers to access the Service without prior written permission.</li>
            <li>Not use the Service to distribute malware, spam, or harmful content.</li>
            <li>Take full responsibility for any financial decisions made based on the results from our calculators.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>6. Intellectual Property</h2>
          <p>
            All content on the Service, including but not limited to text, graphics, code, design, logos, and
            calculator interfaces, is the intellectual property of Calsi or its licensors and is protected by
            applicable copyright, trademark, and intellectual property laws.
          </p>
          <p>
            You may access and use the Service for personal, non-commercial purposes. You may not reproduce,
            distribute, modify, create derivative works of, or commercially exploit any portion of the Service
            without our prior written consent.
          </p>
        </section>

        <section className="legal-section">
          <h2>7. Third-Party Links and Advertising</h2>
          <p>
            The Service may contain links to third-party websites and display advertisements from third-party
            networks (including Google AdSense). We are not responsible for the content, privacy practices, or
            accuracy of any third-party websites or advertisements.
          </p>
          <p>
            Clicking on third-party links or advertisements is done at your own risk. We encourage you to review
            the terms and privacy policies of any third-party websites you visit.
          </p>
        </section>

        <section className="legal-section">
          <h2>8. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by applicable law, Calsi and its affiliates, officers, directors,
            employees, and agents shall not be liable for any:
          </p>
          <ul>
            <li>Indirect, incidental, special, consequential, or punitive damages.</li>
            <li>Loss of profits, revenue, data, or financial losses arising from your use of the Service.</li>
            <li>Financial losses resulting from reliance on calculator results or information provided on the Service.</li>
            <li>Interruptions, errors, or unavailability of the Service.</li>
          </ul>
          <p>
            In no event shall our total liability to you exceed the amount you paid to use the Service (if any)
            in the twelve (12) months preceding the claim, or INR 100 (whichever is greater).
          </p>
        </section>

        <section className="legal-section">
          <h2>9. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless Calsi and its affiliates from and against any
            claims, liabilities, damages, losses, and expenses (including legal fees) arising from:
          </p>
          <ul>
            <li>Your use of or reliance on the Service.</li>
            <li>Your violation of these Terms.</li>
            <li>Your violation of any applicable law or third-party rights.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>10. Availability and Service Interruptions</h2>
          <p>
            We strive to maintain high availability of the Service but do not guarantee uninterrupted access.
            The Service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our
            control. We shall not be liable for any losses arising from Service interruptions.
          </p>
        </section>

        <section className="legal-section">
          <h2>11. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of <strong>India</strong>.
            Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts
            located in India.
          </p>
        </section>

        <section className="legal-section">
          <h2>12. Severability</h2>
          <p>
            If any provision of these Terms is found to be invalid or unenforceable by a court of competent
            jurisdiction, that provision shall be modified to the minimum extent necessary to make it enforceable,
            and the remaining provisions shall continue in full force and effect.
          </p>
        </section>

        <section className="legal-section">
          <h2>13. Entire Agreement</h2>
          <p>
            These Terms, together with our Privacy Policy, constitute the entire agreement between you and Calsi
            with respect to your use of the Service and supersede all prior agreements, understandings, or
            representations.
          </p>
        </section>

        <section className="legal-section">
          <h2>14. Contact Us</h2>
          <p>
            If you have any questions, concerns, or feedback regarding these Terms and Conditions, please
            contact us at:
          </p>
          <div className="legal-contact-box">
            <p><strong>Calsi</strong></p>
            <p>Email: <a href="mailto:legal@calsi.app">legal@calsi.app</a></p>
            <p>Website: <a href="https://calsi.vercel.app" target="_blank" rel="noopener noreferrer">calsi.vercel.app</a></p>
          </div>
        </section>

      </div>
    </div>
  );
}
